### PR TITLE
Add Travis CI Support

### PR DESCRIPTION
**Pull request by arichiv**
It works! https://travis-ci.com/arichiv/seal-rookery/builds/85769043

### CODE REVIEW

**Comment by arichiv** [comment]
@mlissner

**Comment by arichiv** [comment]
Ping @mlissner

**Comment by mlissner** [comment]
I forget, do I have to tell Travis to start doing something here, or will it get on top of this now that I pulled in the .travis.yml file?

**Comment by arichiv** [comment]
@mlissner looks like you might need to go to travis to activate it

**Pull request merged**
